In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('/Users/matin/Library/Mobile Documents/com~apple~CloudDocs/Coding Dojo Python/Track Machine Learning I/Introducción to Machine Learning/KNN/abalone.data')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [4]:
from sklearn.neighbors import KNeighborsRegressor

KNN Regresor 

In [5]:
X = df.loc[:, ['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight','Shell weight']].values

In [6]:
y = df.loc[:, ['Rings']] ## No encuentro la variable edad por tanto supongo que esta es la variable que hay que predecir

In [7]:
neigh = KNeighborsRegressor(n_neighbors=2)

In [8]:
neigh.fit(X, y)

KNeighborsRegressor(n_neighbors=2)

In [9]:
predictions = neigh.predict(X)

In [10]:
predictions

array([[11. ],
       [ 7.5],
       [10. ],
       ...,
       [ 9.5],
       [10. ],
       [12.5]])

In [11]:
score = neigh.score(X, y)
score

0.8005730421070305

## KNN Classifier 

In [12]:
X = df.loc[:, ['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight','Shell weight','Rings']].values

In [13]:
y = df.loc[:, ['Sex']].values

In [14]:
X.shape

(4177, 8)

In [15]:
y

array([['M'],
       ['M'],
       ['F'],
       ...,
       ['M'],
       ['F'],
       ['M']], dtype=object)

In [16]:
knn = KNeighborsClassifier(n_neighbors=5)

In [17]:
knn.fit(X, y)

<ipython-input-17-e49efb2b829f>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(X, y)


KNeighborsClassifier()

In [18]:
predictions = knn.predict(X)

In [19]:
predictions


array(['I', 'I', 'I', ..., 'F', 'M', 'M'], dtype=object)

In [20]:
score = knn.score(X,y)
score

0.6878142207325832

¿Podrías haber utilizado la regresión lineal y la regresión KNN para resolver el problema de regresión?
Sí, ya que se obtiene la estructura de datos con la que se realiza una regresión

¿Podrías haber utilizado la regresión lineal para el problema de clasificación?
No, porque una regresión lineal no se ajusta a modelos con una variable dependiente categórica.

# Validación del modelo

In [33]:
X = df.loc[:, ['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight','Shell weight']].values
y = df.loc[:, ['Rings']] ## No encuentro la variable edad por tanto supongo que esta es la variable que hay que predecir

In [34]:
# Dato de prueba y entrenamiento
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3)

In [36]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [37]:
neigh = KNeighborsRegressor(n_neighbors=2)

In [38]:
print(neigh)

KNeighborsRegressor(n_neighbors=2)


In [39]:
neigh.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=2)

In [40]:
# Podemos ver las predicciones de entrenamiento para ver qué tan bien nuestro modelo se ajusta a los datos de entrenamiento (verificando el sesgo)
predictions = neigh.predict(X_train)

In [41]:
predictions

array([[ 8. ],
       [ 7.5],
       [ 9.5],
       ...,
       [10. ],
       [ 9.5],
       [11.5]])

In [42]:
test_predictions = neigh.predict(X_train)

In [43]:
score = neigh.score(X_train, y_train)
score

0.7850301861105542

In [44]:
test_predictions = neigh.predict(X_test)

In [45]:
score = neigh.score(X_test, y_test)
score

0.32784096497274107

## Regresión lineal

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
reg = LinearRegression(fit_intercept=True)

In [48]:
reg.fit(X,y)

LinearRegression()

In [50]:
reg.predict(X[0].reshape(-1,7))

array([[8.77893882]])

In [52]:
reg.predict(X)

array([[ 8.77893882],
       [ 7.23758471],
       [10.84589582],
       ...,
       [10.88079477],
       [ 9.6174032 ],
       [11.04119896]])

In [53]:
score = reg.score(X, y)
print(score)

0.5276299399919837


In [54]:
# Validación del modelo
reg = LinearRegression(fit_intercept=True)
reg.fit(X_train,y_train)

LinearRegression()

In [55]:
reg.predict(X_train[0].reshape(-1,7))

array([[9.00680975]])

In [56]:
reg.predict(X_train)

array([[ 9.00680975],
       [ 9.42409099],
       [ 9.26016399],
       ...,
       [10.76678039],
       [10.24706852],
       [11.28066559]])

In [57]:
score = reg.score(X_train, y_train)
print(score)

0.5354587218762766


In [58]:
test_predictions = reg.predict(X_test)

In [59]:
score = reg.score(X_test, y_test)
score

0.4980116590773236

¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando no usaste la división entrenar probar?
KNN sin usar datos de prueba y entrenamiento parece que se ajusta mejor ya que su score es de 0.8 y el de regresión lineal es de 0.52

¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando usaste la división entrenar probar? Cuando se corre el modelo en los datos de prueba la regresión lineal tiene un mejor ajuste.

¿Hubo alguna ventaja en la regresión lineal en términos de la cantidad de código que tenías que escribir? No, se tuvo que usar un par de líneas más de código 

¿Hay alguna forma de mostrarle a alguien cuál de los dos modelos fue más efectivo? Utilizando el score de cada modelo se puede mostrar cual fue más efectivo.

¿Crees que podrías haber mejorado KNN para mejorar la eficacia del modelo? Sí, se puede modificar los hiperparámetros del modelo y se puede jugar con el trade off de sesgo y varianza.